"""Central, non-configurable resource limits for the public demo service."""

REQUEST_BODY_MAX_BYTES = 65_536
REQUEST_BODY_READ_TIMEOUT_SECONDS = 4.0

YAML_MAX_ENCODED_BYTES = 24_576
YAML_MAX_ANCHORS = 24
YAML_MAX_ALIASES = 24
YAML_MAX_NESTING_DEPTH = 20
YAML_MAX_SCALARS = 2_048
YAML_MAX_COLLECTIONS = 512
YAML_MAX_EXPANDED_NODES = 4_096
YAML_MAX_EXPANDED_SCALAR_BYTES = 131_072
YAML_RESPONSE_MAX_BYTES = 262_144

CLIENT_RATE_CAPACITY = 30
CLIENT_RATE_REFILL_PER_SECOND = 1.0
GLOBAL_RATE_CAPACITY = 120
GLOBAL_RATE_REFILL_PER_SECOND = 10.0
RATE_LIMIT_MAX_IDENTITIES = 2_048
RATE_LIMIT_IDENTITY_TTL_SECONDS = 300.0

SUBPROCESS_TIMEOUT_SECONDS = 10.0
INTERNAL_DIAGNOSTIC_MAX_BYTES = 8_192
