"""
Stable public API for the Aegis Governance SDK.
"""

import logging

from aegis.enforcement import (
    AEGIS,
    AIGC,
    PreCallResult,
    enforce_invocation,
    enforce_invocation_async,
    enforce_post_call,
    enforce_post_call_async,
    enforce_pre_call,
    enforce_pre_call_async,
)
from aegis.errors import (
    AIGCError,
    ArtifactSigningError,
    AuditSinkError,
    ConditionResolutionError,
    CustomGateViolationError,
    FeatureNotImplementedError,
    GovernanceViolationError,
    GuardEvaluationError,
    InvocationValidationError,
    PolicyLoadError,
    PolicyValidationError,
    PreconditionError,
    RiskThresholdError,
    SchemaValidationError,
    SessionStateError,
    SignatureMetadataError,
    SigningContractError,
    ToolConstraintViolationError,
    VerificationContractError,
    WorkflowApprovalRequiredError,
    WorkflowHandoffDeniedError,
    WorkflowHookDeniedError,
    WorkflowParticipantMismatchError,
    WorkflowProtocolViolationError,
    WorkflowRoleViolationError,
    WorkflowSequenceViolationError,
    WorkflowSessionTokenInvalidError,
    WorkflowSourceRequiredError,
    WorkflowStarterIntegrityError,
    WorkflowStepBudgetExceededError,
    WorkflowToolBudgetExceededError,
    WorkflowTransitionDeniedError,
    WorkflowUnsupportedBindingError,
)
from aegis.session import GovernanceSession, SessionPreCallResult
from aegis.retry import with_retry, RetryExhaustedError
from aegis.sinks import (
    AuditSink,
    CallbackAuditSink,
    JsonFileAuditSink,
    get_audit_sink,
    get_sink_failure_mode,
    set_audit_sink,
    set_sink_failure_mode,
)
from aegis.builder import InvocationBuilder
from aegis.decorators import governed
from aegis.signing import (
    AnchorStatus,
    ArtifactSigner,
    ArtifactVerificationResult,
    CANONICALIZATION_VERSION,
    EvidenceType,
    ExternalArtifactSigner,
    ExternalArtifactVerifier,
    ExternalVerificationOutcome,
    HMACSigner,
    SIGNATURE_METADATA_SCHEMA_VERSION,
    SIGNING_PROFILE,
    SignatureEncoding,
    SignatureMetadata,
    SignatureStatus,
    SignerIdentity,
    SigningReceipt,
    VerificationReasonCode,
    sign_artifact,
    sign_artifact_with_metadata,
    verify_artifact,
    verify_artifact_detailed,
)
from aegis.gates import (
    EnforcementGate,
    GateResult,
    INSERTION_PRE_AUTHORIZATION,
    INSERTION_POST_AUTHORIZATION,
    INSERTION_PRE_OUTPUT,
    INSERTION_POST_OUTPUT,
)
from aegis.audit_chain import (
    AuditChain,
    ChainContinuity,
    ChainVerificationReport,
    Completeness,
    ContentIntegrity,
    VerificationError,
    verify_chain,
    verify_chain_detailed,
)
from aegis._internal.evidence_profiles import (
    EvidenceProfileError,
    build_content_checksum_v2,
    verify_content_checksum_v2,
)
from aegis.lineage import AuditLineage
from aegis.provenance_gate import ProvenanceGate
from aegis.risk_history import (
    RiskHistory,
    TRAJECTORY_DEGRADING,
    TRAJECTORY_IMPROVING,
    TRAJECTORY_STABLE,
)
from aegis.policy_loader import (
    PolicyLoaderBase,
    FilePolicyLoader,
    load_policy,
    merge_policies,
    validate_policy_dates,
    COMPOSITION_INTERSECT,
    COMPOSITION_UNION,
    COMPOSITION_REPLACE,
)
from aegis.risk_scoring import (
    compute_risk_score,
    RiskScore,
    RISK_MODE_STRICT,
    RISK_MODE_RISK_SCORED,
    RISK_MODE_WARN_ONLY,
)
from aegis.policy_testing import (
    PolicyTestCase,
    PolicyTestResult,
    PolicyTestSuite,
    expect_pass,
    expect_fail,
)

# Register NullHandler so library users don't see "No handlers found" warnings.
# Host applications configure log levels and handlers on their own loggers.
logging.getLogger("aegis").addHandler(logging.NullHandler())

__version__ = "0.9.0b1"

__all__ = [
    "AEGIS",
    "AIGC",
    "AIGCError",
    "AnchorStatus",
    "GovernanceSession",
    "PreCallResult",
    "SessionPreCallResult",
    "SessionStateError",
    "ArtifactSigner",
    "ArtifactSigningError",
    "ArtifactVerificationResult",
    "AuditChain",
    "ChainContinuity",
    "ChainVerificationReport",
    "AuditLineage",
    "AuditSink",
    "AuditSinkError",
    "COMPOSITION_INTERSECT",
    "COMPOSITION_REPLACE",
    "COMPOSITION_UNION",
    "CallbackAuditSink",
    "CANONICALIZATION_VERSION",
    "ConditionResolutionError",
    "Completeness",
    "ContentIntegrity",
    "CustomGateViolationError",
    "EnforcementGate",
    "EvidenceType",
    "EvidenceProfileError",
    "ExternalArtifactSigner",
    "ExternalArtifactVerifier",
    "ExternalVerificationOutcome",
    "FeatureNotImplementedError",
    "FilePolicyLoader",
    "GateResult",
    "GovernanceViolationError",
    "GuardEvaluationError",
    "HMACSigner",
    "INSERTION_POST_AUTHORIZATION",
    "INSERTION_POST_OUTPUT",
    "INSERTION_PRE_AUTHORIZATION",
    "INSERTION_PRE_OUTPUT",
    "InvocationBuilder",
    "InvocationValidationError",
    "JsonFileAuditSink",
    "PolicyLoadError",
    "PolicyLoaderBase",
    "PolicyTestCase",
    "PolicyTestResult",
    "PolicyTestSuite",
    "PolicyValidationError",
    "ProvenanceGate",
    "PreconditionError",
    "RISK_MODE_RISK_SCORED",
    "RISK_MODE_STRICT",
    "RISK_MODE_WARN_ONLY",
    "RetryExhaustedError",
    "RiskHistory",
    "RiskScore",
    "RiskThresholdError",
    "SchemaValidationError",
    "SIGNATURE_METADATA_SCHEMA_VERSION",
    "SIGNING_PROFILE",
    "ToolConstraintViolationError",
    "SignatureEncoding",
    "SignatureMetadata",
    "SignatureMetadataError",
    "SignatureStatus",
    "SignerIdentity",
    "SigningContractError",
    "SigningReceipt",
    "VerificationContractError",
    "VerificationError",
    "VerificationReasonCode",
    "WorkflowApprovalRequiredError",
    "WorkflowHandoffDeniedError",
    "WorkflowHookDeniedError",
    "WorkflowParticipantMismatchError",
    "WorkflowProtocolViolationError",
    "WorkflowRoleViolationError",
    "WorkflowSequenceViolationError",
    "WorkflowSessionTokenInvalidError",
    "WorkflowSourceRequiredError",
    "WorkflowStarterIntegrityError",
    "WorkflowStepBudgetExceededError",
    "WorkflowToolBudgetExceededError",
    "WorkflowTransitionDeniedError",
    "WorkflowUnsupportedBindingError",
    "TRAJECTORY_DEGRADING",
    "TRAJECTORY_IMPROVING",
    "TRAJECTORY_STABLE",
    "compute_risk_score",
    "enforce_invocation",
    "enforce_invocation_async",
    "enforce_post_call",
    "enforce_post_call_async",
    "enforce_pre_call",
    "enforce_pre_call_async",
    "expect_fail",
    "build_content_checksum_v2",
    "expect_pass",
    "get_audit_sink",
    "get_sink_failure_mode",
    "governed",
    "load_policy",
    "merge_policies",
    "set_audit_sink",
    "set_sink_failure_mode",
    "sign_artifact",
    "sign_artifact_with_metadata",
    "validate_policy_dates",
    "verify_artifact",
    "verify_artifact_detailed",
    "verify_chain",
    "verify_chain_detailed",
    "verify_content_checksum_v2",
    "with_retry",
]
