"""
workflow lint — static diagnostics for AEGIS governance targets.

Supported target kinds:
- ``policy``         — a YAML policy file
- ``starter_dir``    — a directory generated by ``aegis workflow init``
- ``workflow_artifact`` — a JSON workflow artifact
- ``audit_artifact`` — a JSON invocation audit artifact

Each public function returns a list of finding dicts:
    {
        "code":        str,   # machine-readable code (e.g. "POLICY_LOAD_ERROR")
        "message":     str,   # human-readable description
        "target_kind": str,   # "policy" | "starter_dir" | "workflow_artifact" | "audit_artifact"
        "path":        str,   # absolute path that was checked
    }

An empty list means the target is clean.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft7Validator

from aegis._internal.policy_loader import SCHEMAS_DIR
from aegis._internal.errors import PolicyLoadError, PolicyValidationError
from aegis._internal.policy_compiler import compile_policy


# ---------------------------------------------------------------------------
# Schema loading (lazy, cached at module level)
# ---------------------------------------------------------------------------

_WORKFLOW_SCHEMA: dict | None = None
_AUDIT_SCHEMA: dict | None = None
_UNSUPPORTED_PROTOCOLS = frozenset({"grpc", "websocket", "soap"})
_MAX_WITNESS_TRACE_EVENTS = 8


def _workflow_schema() -> dict:
    global _WORKFLOW_SCHEMA
    if _WORKFLOW_SCHEMA is None:
        path = SCHEMAS_DIR / "workflow_artifact.schema.json"
        _WORKFLOW_SCHEMA = json.loads(path.read_text(encoding="utf-8"))
    return _WORKFLOW_SCHEMA


def _audit_schema() -> dict:
    global _AUDIT_SCHEMA
    if _AUDIT_SCHEMA is None:
        path = SCHEMAS_DIR / "audit_artifact.schema.json"
        _AUDIT_SCHEMA = json.loads(path.read_text(encoding="utf-8"))
    return _AUDIT_SCHEMA


# ---------------------------------------------------------------------------
# Finding constructor and bounded evidence helpers
# ---------------------------------------------------------------------------

def _json_safe(value: Any) -> Any:
    """Return a JSON-serializable copy of deterministic lint evidence."""
    return json.loads(json.dumps(value, default=str))


def _event_dict(event: Any) -> dict[str, Any]:
    if isinstance(event, dict):
        return dict(event)
    return {"kind": "evidence", "value": event}


def _bounded_witness_trace(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    safe_events = [_event_dict(event) for event in _json_safe(events)]
    if len(safe_events) <= _MAX_WITNESS_TRACE_EVENTS:
        return safe_events
    capped = safe_events[:_MAX_WITNESS_TRACE_EVENTS]
    capped[-1] = {**capped[-1], "truncated": True}
    return capped


def _bounded_witness_trace_with_final(
    events: list[dict[str, Any]],
    final_event: dict[str, Any],
) -> list[dict[str, Any]]:
    safe_events = [_event_dict(event) for event in _json_safe(events)]
    safe_final = _event_dict(_json_safe(final_event))
    if len(safe_events) < _MAX_WITNESS_TRACE_EVENTS:
        return safe_events + [safe_final]
    prefix = safe_events[: max(0, _MAX_WITNESS_TRACE_EVENTS - 1)]
    if prefix:
        prefix[-1] = {**prefix[-1], "truncated": True}
    return prefix + [safe_final]


def _finding(
    code: str,
    message: str,
    target_kind: str,
    path: str,
    *,
    details: dict[str, Any] | None = None,
    witness_trace: list[dict[str, Any]] | None = None,
) -> dict:
    finding = {"code": code, "message": message, "target_kind": target_kind, "path": path}
    if details:
        finding["details"] = _json_safe(details)
    if witness_trace:
        finding["witness_trace"] = _bounded_witness_trace(witness_trace)
    return finding


# ---------------------------------------------------------------------------
# Workflow graph/topology lint helpers
# ---------------------------------------------------------------------------

def _normalize_required_sequence(workflow: dict[str, Any]) -> list[str]:
    required_sequence = workflow.get("required_sequence")
    if not isinstance(required_sequence, list):
        return []
    return [step for step in required_sequence if isinstance(step, str)]


def _normalize_transition_graph(workflow: dict[str, Any]) -> dict[str, list[str]]:
    allowed_transitions = workflow.get("allowed_transitions")
    if not isinstance(allowed_transitions, dict):
        return {}
    graph: dict[str, list[str]] = {}
    for from_step, to_steps in allowed_transitions.items():
        if not isinstance(from_step, str) or not isinstance(to_steps, list):
            continue
        graph[from_step] = sorted({to_step for to_step in to_steps if isinstance(to_step, str)})
    return dict(sorted(graph.items()))


def _find_reachable_steps(
    start_step: str,
    transitions: dict[str, list[str]],
) -> tuple[set[str], list[dict[str, Any]]]:
    reachable = {start_step}
    witness_trace: list[dict[str, Any]] = []
    queue = [start_step]

    while queue:
        current = queue.pop(0)
        for next_step in transitions.get(current, []):
            if next_step in reachable:
                continue
            reachable.add(next_step)
            queue.append(next_step)
            witness_trace.append({
                "kind": "transition",
                "from_step": current,
                "to_step": next_step,
                "reason": "reachable",
            })

    return reachable, _bounded_witness_trace(witness_trace)


def _first_required_sequence_transition_conflict(
    required_sequence: list[str],
    transitions: dict[str, list[str]],
) -> dict[str, Any] | None:
    for current_step, next_step in zip(required_sequence, required_sequence[1:]):
        allowed_next_steps = transitions.get(current_step, [])
        if next_step not in allowed_next_steps:
            return {
                "from_step": current_step,
                "required_next_step": next_step,
                "allowed_next_steps": allowed_next_steps,
            }
    return None


def _participant_roles(workflow: dict[str, Any]) -> dict[str, set[str]]:
    participants = workflow.get("participants") or []
    roles_by_id: dict[str, set[str]] = {}
    if not isinstance(participants, list):
        return roles_by_id
    for participant in participants:
        if not isinstance(participant, dict):
            continue
        participant_id = participant.get("id")
        if not isinstance(participant_id, str):
            continue
        roles = {
            role for role in (participant.get("roles") or []) if isinstance(role, str)
        }
        roles_by_id[participant_id] = roles
    return roles_by_id


def _find_unbounded_handoff_cycle(
    workflow: dict[str, Any],
) -> dict[str, Any] | None:
    if workflow.get("max_steps") is not None:
        return None

    escalation = workflow.get("escalation") or {}
    if not isinstance(escalation, dict):
        escalation = {}
    if escalation.get("require_approval_after_steps") is not None:
        return None

    approval_roles = {
        role
        for role in (escalation.get("require_approval_for_roles") or [])
        if isinstance(role, str)
    }
    roles_by_id = _participant_roles(workflow)

    handoffs = workflow.get("handoffs") or []
    if not isinstance(handoffs, list):
        return None

    graph: dict[str, set[str]] = {}
    for handoff in handoffs:
        if not isinstance(handoff, dict):
            continue
        from_participant = handoff.get("from")
        to_participant = handoff.get("to")
        if not isinstance(from_participant, str) or not isinstance(to_participant, str):
            continue
        graph.setdefault(from_participant, set()).add(to_participant)
        graph.setdefault(to_participant, set())

    def _cycle_has_approval_break(cycle: list[str]) -> bool:
        cycle_roles: set[str] = set()
        for participant_id in cycle[:-1]:
            cycle_roles.update(roles_by_id.get(participant_id, set()))
        return bool(approval_roles & cycle_roles)

    def _dfs(node: str, path: list[str]) -> list[str] | None:
        for next_node in sorted(graph.get(node, set())):
            if next_node in path:
                cycle = path[path.index(next_node):] + [next_node]
                if not _cycle_has_approval_break(cycle):
                    return cycle
                continue
            result = _dfs(next_node, path + [next_node])
            if result is not None:
                return result
        return None

    for start_node in sorted(graph):
        cycle = _dfs(start_node, [start_node])
        if cycle is not None:
            participants = list(dict.fromkeys(cycle[:-1]))
            return {
                "participants": participants,
                "cycle": cycle,
                "budget_rule": None,
                "approval_break": None,
            }

    return None


def _ordered_reachable_steps(
    reachable: set[str],
    required_sequence: list[str],
) -> list[str]:
    required_set = set(required_sequence)
    ordered = [step for step in required_sequence if step in reachable]
    ordered.extend(sorted(step for step in reachable if step not in required_set))
    return ordered


def _known_predecessors(step_id: str, transitions: dict[str, list[str]]) -> list[str]:
    return sorted(
        from_step for from_step, to_steps in transitions.items() if step_id in to_steps
    )


def _has_unknown_transition_step_refs(
    workflow: dict[str, Any],
    declared_steps: set[str],
) -> bool:
    allowed_transitions = workflow.get("allowed_transitions") or {}
    if not isinstance(allowed_transitions, dict) or not declared_steps:
        return False
    for from_step, to_steps in allowed_transitions.items():
        if isinstance(from_step, str) and from_step not in declared_steps:
            return True
        if not isinstance(to_steps, list):
            continue
        if any(isinstance(to_step, str) and to_step not in declared_steps for to_step in to_steps):
            return True
    return False


def _has_unknown_handoff_participant_refs(workflow: dict[str, Any]) -> bool:
    participants = workflow.get("participants") or []
    participant_ids = {
        participant.get("id")
        for participant in participants
        if isinstance(participant, dict) and isinstance(participant.get("id"), str)
    }
    handoffs = workflow.get("handoffs") or []
    if not participant_ids or not isinstance(handoffs, list):
        return False
    for handoff in handoffs:
        if not isinstance(handoff, dict):
            continue
        for endpoint_key in ("from", "to"):
            endpoint = handoff.get(endpoint_key)
            if isinstance(endpoint, str) and endpoint not in participant_ids:
                return True
    return False


def _lint_workflow_graph(
    workflow: dict[str, Any],
    *,
    target_kind: str,
    path: Path,
) -> list[dict]:
    findings: list[dict] = []
    required_sequence = _normalize_required_sequence(workflow)
    transitions = _normalize_transition_graph(workflow)
    declared_steps = set(required_sequence)

    if (
        required_sequence
        and not _has_unknown_transition_step_refs(workflow, declared_steps)
    ):
        start_step = required_sequence[0]
        reachable, traversal_trace = _find_reachable_steps(start_step, transitions)

        unreachable_step = next(
            (step for step in required_sequence if step not in reachable),
            None,
        )
        if unreachable_step is not None:
            findings.append(_finding(
                "WORKFLOW_UNREACHABLE_STEP",
                f"workflow.required_sequence declares step {unreachable_step!r} "
                "but it is not reachable from the start step through "
                "workflow.allowed_transitions.",
                target_kind,
                str(path),
                details={
                    "declared_step": unreachable_step,
                    "start_step": start_step,
                    "known_predecessors": _known_predecessors(unreachable_step, transitions),
                    "reachable_steps": _ordered_reachable_steps(reachable, required_sequence),
                },
                witness_trace=_bounded_witness_trace_with_final(
                    traversal_trace,
                    {
                        "kind": "blocked_step",
                        "step_id": unreachable_step,
                        "reason": "not_reachable_from_start",
                    },
                ),
            ))

        for index, step_id in enumerate(required_sequence[:-1]):
            valid_next_steps = [
                step for step in transitions.get(step_id, []) if step in set(required_sequence)
            ]
            if valid_next_steps:
                continue
            findings.append(_finding(
                "WORKFLOW_DEAD_END_STEP",
                f"workflow.allowed_transitions gives non-terminal step {step_id!r} "
                "no valid next step, so later required steps cannot run.",
                target_kind,
                str(path),
                details={
                    "step_id": step_id,
                    "valid_next_steps": valid_next_steps,
                    "remaining_required_steps": required_sequence[index + 1:],
                },
                witness_trace=[{
                    "kind": "dead_end",
                    "step_id": step_id,
                    "reason": "no_declared_successor",
                }],
            ))

        conflict = _first_required_sequence_transition_conflict(
            required_sequence,
            transitions,
        )
        if conflict is not None:
            findings.append(_finding(
                "WORKFLOW_REQUIRED_SEQUENCE_IMPOSSIBLE",
                f"workflow.required_sequence requires {conflict['from_step']!r} "
                f"before {conflict['required_next_step']!r}, but "
                "workflow.allowed_transitions does not allow that transition.",
                target_kind,
                str(path),
                details={
                    "required_sequence": required_sequence,
                    "conflicting_rule": f"allowed_transitions.{conflict['from_step']}",
                    "from_step": conflict["from_step"],
                    "required_next_step": conflict["required_next_step"],
                    "allowed_next_steps": conflict["allowed_next_steps"],
                },
                witness_trace=[
                    {
                        "kind": "required_pair",
                        "from_step": conflict["from_step"],
                        "to_step": conflict["required_next_step"],
                        "reason": "required_sequence",
                    },
                    {
                        "kind": "transition_missing",
                        "from_step": conflict["from_step"],
                        "to_step": conflict["required_next_step"],
                        "reason": "not_allowed_by_allowed_transitions",
                    },
                ],
            ))

    handoff_cycle = (
        None
        if _has_unknown_handoff_participant_refs(workflow)
        else _find_unbounded_handoff_cycle(workflow)
    )
    if handoff_cycle is not None:
        findings.append(_finding(
            "WORKFLOW_UNBOUNDED_HANDOFF_LOOP",
            "workflow.handoffs allows a participant cycle without max_steps "
            "or an approval break.",
            target_kind,
            str(path),
            details=handoff_cycle,
            witness_trace=[{
                "kind": "handoff_cycle",
                "cycle": handoff_cycle["cycle"],
                "reason": "no_budget_or_approval_break",
            }],
        ))

    return findings


# ---------------------------------------------------------------------------
# Auto-detection of target kind
# ---------------------------------------------------------------------------

def detect_target_kind(path: str) -> str:
    """
    Infer the target kind from path.

    Returns one of: "policy", "starter_dir", "workflow_artifact", "audit_artifact",
    or "unknown" if no match.
    """
    p = Path(path)
    if not p.exists():
        return "unknown"

    if p.is_dir():
        has_policy = (p / "policy.yaml").is_file()
        has_workflow = (p / "workflow_example.py").is_file()
        has_readme = (p / "README.md").is_file()
        if has_policy and has_workflow and has_readme:
            return "starter_dir"
        return "unknown"

    suffix = p.suffix.lower()
    if suffix in (".yaml", ".yml"):
        return "policy"

    if suffix == ".json":
        try:
            raw = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return "unknown"
        if isinstance(raw, dict) and raw.get("artifact_type") == "workflow":
            return "workflow_artifact"
        # Check against audit schema shape (required fields)
        if isinstance(raw, dict) and "enforcement_result" in raw and "audit_schema_version" in raw:
            return "audit_artifact"
        return "unknown"

    return "unknown"


# ---------------------------------------------------------------------------
# Policy lint
# ---------------------------------------------------------------------------

def lint_policy(path: str, *, target_kind: str = "policy") -> list[dict]:
    """
    Lint a policy YAML file.

    Checks performed:
    1. File readability
    2. YAML parse
    3. Root must be a mapping
    4. JSON-schema validation against policy_dsl.schema.json
    5. Date consistency: effective_date <= expiration_date
    6. Duplicate entries in tools.allowed_tools
    7. output_schema must itself be a valid Draft 7 JSON schema
    """
    findings: list[dict] = []
    p = Path(path)

    # 1. Readability
    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read policy file: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    # 2. YAML parse
    try:
        policy = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"YAML parse error: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    # 3. Root type
    if not isinstance(policy, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Policy file must be a YAML mapping (dict), got "
            f"{type(policy).__name__}.",
            target_kind,
            str(p),
        ))
        return findings

    # 4. Shared compiler semantics. Lint surfaces the compiler's stable code
    # and path rather than maintaining a second authorization interpretation.
    try:
        compile_policy(policy, source=str(p), allow_legacy=False)
    except (PolicyLoadError, PolicyValidationError) as exc:
        details = (
            dict(exc.details)
            if isinstance(exc.details, dict)
            else {}
        )
        findings.append(_finding(
            exc.code,
            str(exc),
            target_kind,
            str(p),
            details=details,
        ))
        return findings

    # 6. Date consistency
    eff = policy.get("effective_date")
    exp = policy.get("expiration_date")
    if eff and exp and eff > exp:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"effective_date ({eff}) is after expiration_date ({exp}); "
            "policy can never be valid.",
            target_kind,
            str(p),
        ))

    # 7. output_schema well-formedness
    output_schema = policy.get("output_schema")
    if output_schema is not None and isinstance(output_schema, dict):
        try:
            Draft7Validator.check_schema(output_schema)
        except Exception as exc:
            findings.append(_finding(
                "POLICY_SCHEMA_VALIDATION_ERROR",
                f"output_schema is not a valid JSON Schema Draft 7: {exc}",
                target_kind,
                str(p),
            ))

    workflow = policy.get("workflow") or {}
    if isinstance(workflow, dict):
        required_sequence = workflow.get("required_sequence") or []
        if (
            isinstance(required_sequence, list)
            and isinstance(workflow.get("max_steps"), int)
            and len(required_sequence) > workflow["max_steps"]
        ):
            findings.append(_finding(
                "WORKFLOW_STEP_BUDGET_EXCEEDED",
                "workflow.required_sequence length exceeds workflow.max_steps; "
                "the declared sequence cannot complete within the configured budget.",
                target_kind,
                str(p),
                details={
                    "required_sequence_length": len(required_sequence),
                    "max_steps": workflow["max_steps"],
                    "conflicting_rule": "workflow.max_steps",
                },
            ))

        declared_steps = {
            step_id for step_id in required_sequence if isinstance(step_id, str)
        }
        allowed_transitions = workflow.get("allowed_transitions") or {}
        if isinstance(allowed_transitions, dict) and declared_steps:
            for from_step, to_steps in allowed_transitions.items():
                if from_step not in declared_steps:
                    findings.append(_finding(
                        "WORKFLOW_INVALID_TRANSITION",
                        f"allowed_transitions references unknown from-step {from_step!r}; "
                        "declare it in workflow.required_sequence.",
                        target_kind,
                        str(p),
                    ))
                if not isinstance(to_steps, list):
                    continue
                for to_step in to_steps:
                    if isinstance(to_step, str) and to_step not in declared_steps:
                        findings.append(_finding(
                            "WORKFLOW_INVALID_TRANSITION",
                            f"allowed_transitions references unknown to-step {to_step!r}; "
                            "declare it in workflow.required_sequence.",
                            target_kind,
                            str(p),
                        ))

        participants = workflow.get("participants") or []
        participant_ids = {
            participant.get("id")
            for participant in participants
            if isinstance(participant, dict) and isinstance(participant.get("id"), str)
        }
        handoffs = workflow.get("handoffs") or []
        if participant_ids and isinstance(handoffs, list):
            for handoff in handoffs:
                if not isinstance(handoff, dict):
                    continue
                for endpoint_key in ("from", "to"):
                    endpoint = handoff.get(endpoint_key)
                    if isinstance(endpoint, str) and endpoint not in participant_ids:
                        findings.append(_finding(
                            "WORKFLOW_INVALID_TRANSITION",
                            f"handoffs entry references unknown participant {endpoint!r}; "
                            "declare it in workflow.participants.",
                            target_kind,
                            str(p),
                        ))

        protocol_constraints = workflow.get("protocol_constraints") or {}
        unsupported_protocols = set()
        if isinstance(protocol_constraints, dict):
            unsupported_protocols.update(
                protocol
                for protocol in protocol_constraints
                if isinstance(protocol, str) and protocol.lower() in _UNSUPPORTED_PROTOCOLS
            )
        if isinstance(participants, list):
            for participant in participants:
                if not isinstance(participant, dict):
                    continue
                for protocol in participant.get("protocols") or []:
                    if isinstance(protocol, str) and protocol.lower() in _UNSUPPORTED_PROTOCOLS:
                        unsupported_protocols.add(protocol)
        if unsupported_protocols:
            findings.append(_finding(
                "WORKFLOW_UNSUPPORTED_BINDING",
                "workflow policy references unsupported protocols: "
                f"{sorted(unsupported_protocols)}. Only local, bedrock, and a2a "
                "workflow protocol constraints are supported in v0.9.0.",
                target_kind,
                str(p),
            ))

        findings.extend(_lint_workflow_graph(
            workflow,
            target_kind=target_kind,
            path=p,
        ))

    return findings


# ---------------------------------------------------------------------------
# Starter directory lint
# ---------------------------------------------------------------------------

_INTERNAL_IMPORT_RE = re.compile(
    r"(?:^|\n)\s*(?:from|import)\s+aegis\._internal"
)


def lint_starter_dir(path: str) -> list[dict]:
    """
    Lint a starter directory generated by ``aegis workflow init``.

    Checks:
    - Required files exist (policy.yaml, workflow_example.py, README.md)
    - All required files are non-empty
    - policy.yaml passes policy lint
    - workflow_example.py parses as valid Python (AST)
    - workflow_example.py does not import aegis._internal
    """
    findings: list[dict] = []
    p = Path(path)

    required_files = ["policy.yaml", "workflow_example.py", "README.md"]
    for fname in required_files:
        fpath = p / fname
        if not fpath.is_file():
            findings.append(_finding(
                "WORKFLOW_STARTER_INTEGRITY_ERROR",
                f"Required file '{fname}' is missing from starter directory.",
                "starter_dir",
                str(p),
            ))
            continue
        if fpath.stat().st_size == 0:
            findings.append(_finding(
                "WORKFLOW_STARTER_INTEGRITY_ERROR",
                f"Required file '{fname}' is empty.",
                "starter_dir",
                str(p),
            ))

    # Stop here if files are missing — subsequent checks will error
    if any(f["code"] == "WORKFLOW_STARTER_INTEGRITY_ERROR" for f in findings):
        return findings

    # Lint nested policy.yaml
    nested_policy = str(p / "policy.yaml")
    policy_findings = lint_policy(nested_policy, target_kind="starter_dir")
    findings.extend(policy_findings)

    # Validate workflow_example.py
    workflow_py = p / "workflow_example.py"
    try:
        source = workflow_py.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"Cannot read workflow_example.py: {exc}",
            "starter_dir",
            str(p),
        ))
        return findings

    # AST parse check
    try:
        ast.parse(source)
    except SyntaxError as exc:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"workflow_example.py has a syntax error: {exc}",
            "starter_dir",
            str(p),
        ))

    # Public-import safety check
    if _INTERNAL_IMPORT_RE.search(source):
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            "workflow_example.py imports from aegis._internal, which is not "
            "part of the public API. Use public aegis imports only.",
            "starter_dir",
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Workflow artifact lint
# ---------------------------------------------------------------------------

def lint_workflow_artifact(path: str) -> list[dict]:
    """
    Lint a serialized workflow artifact JSON file.

    Checks:
    - JSON parse
    - Schema validation against workflow_artifact.schema.json
    - len(invocation_audit_checksums) == len(steps)
    - failure_summary present for FAILED artifacts, absent/null for others
    """
    findings: list[dict] = []
    p = Path(path)

    # JSON parse
    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read workflow artifact: {exc}",
            "workflow_artifact",
            str(p),
        ))
        return findings

    try:
        artifact: Any = json.loads(raw)
    except json.JSONDecodeError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"JSON parse error in workflow artifact: {exc}",
            "workflow_artifact",
            str(p),
        ))
        return findings

    if not isinstance(artifact, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Workflow artifact must be a JSON object.",
            "workflow_artifact",
            str(p),
        ))
        return findings

    # Schema validation
    schema = _workflow_schema()
    validator = Draft7Validator(schema)
    schema_errors = sorted(validator.iter_errors(artifact), key=lambda e: list(e.path))
    for err in schema_errors:
        pointer = ".".join(str(seg) for seg in err.absolute_path) or "$"
        findings.append(_finding(
            "POLICY_SCHEMA_VALIDATION_ERROR",
            f"Workflow artifact schema violation at {pointer}: {err.message}",
            "workflow_artifact",
            str(p),
        ))
    if findings:
        return findings

    # Validate every step entry is a mapping (schema only enforces array type)
    steps = artifact.get("steps", [])
    for idx, step in enumerate(steps):
        if not isinstance(step, dict):
            findings.append(_finding(
                "WORKFLOW_STARTER_INTEGRITY_ERROR",
                f"steps[{idx}] is {type(step).__name__!r}, expected object. "
                "Artifact may be corrupt.",
                "workflow_artifact",
                str(p),
            ))
    if findings:
        return findings

    # Checksum / step count consistency
    checksums = artifact.get("invocation_audit_checksums", [])
    if len(checksums) != len(steps):
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"invocation_audit_checksums length ({len(checksums)}) does not "
            f"match steps length ({len(steps)}). Artifact may be corrupt.",
            "workflow_artifact",
            str(p),
        ))

    missing_step_checksums = [
        idx
        for idx, step in enumerate(steps)
        if not isinstance(step.get("invocation_artifact_checksum"), str)
        or not step.get("invocation_artifact_checksum")
    ]
    if missing_step_checksums:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            "Workflow artifact has steps with missing or invalid "
            "invocation_artifact_checksum values at indexes "
            f"{missing_step_checksums}. Artifact may be incomplete or corrupt.",
            "workflow_artifact",
            str(p),
        ))

    # failure_summary consistency
    status = artifact.get("status", "")
    failure_summary = artifact.get("failure_summary")
    if status == "FAILED" and not failure_summary:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            "Workflow artifact has status FAILED but failure_summary is "
            "absent or null. Artifact may be incomplete.",
            "workflow_artifact",
            str(p),
        ))
    elif status != "FAILED" and failure_summary is not None:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"Workflow artifact has status {status!r} but failure_summary "
            "is non-null. Unexpected state.",
            "workflow_artifact",
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Audit artifact lint
# ---------------------------------------------------------------------------

def lint_audit_artifact(path: str, *, target_kind: str = "audit_artifact") -> list[dict]:
    """
    Lint an invocation audit artifact JSON file.

    Checks performed:
    1. File readability
    2. JSON parse
    3. Root must be a JSON object
    4. JSON-schema validation against audit_artifact.schema.json
    """
    findings: list[dict] = []
    p = Path(path)

    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read audit artifact: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    try:
        artifact = json.loads(raw)
    except json.JSONDecodeError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"JSON parse error in audit artifact: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    if not isinstance(artifact, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Audit artifact must be a JSON object.",
            target_kind,
            str(p),
        ))
        return findings

    schema = _audit_schema()
    validator = Draft7Validator(schema)
    schema_errors = sorted(validator.iter_errors(artifact), key=lambda e: list(e.path))
    for err in schema_errors:
        pointer = ".".join(str(seg) for seg in err.absolute_path) or "$"
        findings.append(_finding(
            "POLICY_SCHEMA_VALIDATION_ERROR",
            f"Audit artifact schema violation at {pointer}: {err.message}",
            target_kind,
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Unified entry-point
# ---------------------------------------------------------------------------

def lint_target(path: str, *, kind: str = "auto") -> list[dict]:
    """
    Lint any supported target.

    Args:
        path: Path to the target (file or directory).
        kind: One of "auto", "policy", "starter_dir", "workflow_artifact",
              or "audit_artifact".
              When "auto", the kind is inferred from the path.

    Returns:
        List of finding dicts (empty = clean).
    """
    if kind == "auto":
        kind = detect_target_kind(path)

    if kind == "policy":
        return lint_policy(path)
    elif kind == "starter_dir":
        return lint_starter_dir(path)
    elif kind == "workflow_artifact":
        return lint_workflow_artifact(path)
    elif kind == "audit_artifact":
        return lint_audit_artifact(path)
    else:
        return [_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot determine target kind for: {path}. "
            "Supported targets: .yaml/.yml policy files, starter directories "
            "(containing policy.yaml + workflow_example.py + README.md), "
            "workflow artifact .json files, and invocation audit artifact "
            ".json files.",
            "unknown",
            path,
        )]
